# Generated by Django 5.0.14 on 2026-06-16
from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_initial_data(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    User = apps.get_model('authentication', 'User')

    # Seed Headquarters and Branch 001
    hq_branch = Branch.objects.create(
        id='hq-branch',
        branch_code='HQ001',
        branch_name='Headquarters Branch',
        branch_type='headquarters',
        email='futurekelly360@gmail.com',
        phone='+255678302135',
        address='100 Church St, New York, NY 10001',
        is_active=True
    )
    
    branch_001 = Branch.objects.create(
        id='branch-001',
        branch_code='BR001',
        branch_name='Branch 001',
        branch_type='satellite',
        email='futurekelly360@gmail.com',
        phone='+255678302135',
        address='200 Satellite Rd, Los Angeles, CA 90001',
        is_active=True
    )

    # Seed default users
    # Super Admin (branch=None is allowed)
    User.objects.create(
        email='superadmin@churchnexus.com',
        password=make_password('SuperAdmin123!'),
        role='super_admin',
        branch=None,
        is_staff=True,
        is_superuser=True,
        first_name='Kelvin',
        last_name='Mbise'
    )

    # Church Admin (requires branch assignment)
    User.objects.create(
        email='churchadmin@churchnexus.com',
        password=make_password('ChurchAdmin123!'),
        role='church_admin',
        branch=hq_branch,
        is_staff=False,
        is_superuser=False,
        first_name='Church',
        last_name='Admin'
    )

    # Pastor (requires branch assignment)
    User.objects.create(
        email='pastor@churchnexus.com',
        password=make_password('Pastor123!'),
        role='pastor',
        branch=hq_branch,
        is_staff=False,
        is_superuser=False,
        first_name='John',
        last_name='Pastor'
    )

    # Treasurer (requires branch assignment)
    User.objects.create(
        email='treasurer@churchnexus.com',
        password=make_password('Treasurer123!'),
        role='treasurer',
        branch=hq_branch,
        is_staff=False,
        is_superuser=False,
        first_name='Sarah',
        last_name='Treasurer'
    )

def reverse_seed_initial_data(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    User = apps.get_model('authentication', 'User')

    # Delete users
    User.objects.filter(email__in=[
        'superadmin@churchnexus.com',
        'churchadmin@churchnexus.com',
        'pastor@churchnexus.com',
        'treasurer@churchnexus.com'
    ]).delete()

    # Delete branches
    Branch.objects.filter(id__in=['hq-branch', 'branch-001']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, reverse_code=reverse_seed_initial_data),
    ]
