# Generated by Django 5.0.14 on 2026-06-16 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('Sunday Service', 'Sunday Service'), ('Bible Study', 'Bible Study'), ('Prayer Meeting', 'Prayer Meeting'), ('Youth Meeting', 'Youth Meeting'), ('Conference', 'Conference'), ('Seminar', 'Seminar'), ('Outreach', 'Outreach'), ('Livestream Event', 'Livestream Event'), ('Special Event', 'Special Event')], db_index=True, max_length=50)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('waitlist_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Published', 'Published'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=30)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=30, null=True)),
                ('attendance_snapshot', models.JSONField(blank=True, null=True)),
                ('snapshot_generated_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_version', models.IntegerField(default=1)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('WAITLISTED', 'Waitlisted'), ('PROMOTED', 'Promoted'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], db_index=True, default='REGISTERED', max_length=30)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_status', models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked In'), ('absent', 'Absent')], db_index=True, default='registered', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registration_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_eventregistrations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_eventregistrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_eventregistrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('check_in_method', models.CharField(choices=[('MANUAL', 'Manual'), ('QR_CODE', 'QR Code'), ('SELF_SERVICE', 'Self Service'), ('IMPORT', 'Import')], db_index=True, default='MANUAL', max_length=30)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_eventcheckins', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checkins', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_eventcheckins', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_eventcheckins', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='events.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Venue', 'Venue'), ('Equipment', 'Equipment')], max_length=30)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved')], db_index=True, default='Available', max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='events.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventresource')),
            ],
        ),
    ]
