# Generated by Django 5.0.14 on 2026-06-23 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Healing', 'Healing'), ('Provision', 'Provision'), ('Restoration', 'Restoration'), ('Salvation', 'Salvation'), ('Deliverance', 'Deliverance'), ('Family', 'Family'), ('Education', 'Education'), ('Business', 'Business'), ('General', 'General')], default='General', max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('views', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='branches.branch')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
