# Generated by Django 5.0.14 on 2026-06-17 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceKPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Custom', 'Custom')], db_index=True, max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('total_giving_ytd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('giving_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('avg_weekly_attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_members', models.IntegerField(default=0)),
                ('members_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_snapshots', to='branches.branch')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancekpisnapshot',
            constraint=models.UniqueConstraint(fields=('branch', 'reporting_period', 'start_date', 'end_date'), name='unique_branch_period_range_snapshot'),
        ),
    ]
