# Generated by Django 5.0.14 on 2026-06-17 06:47

from django.db import migrations

DEFAULT_ACCOUNTS = [
    {'code': '1110', 'name': 'Main Operating Bank Account', 'type': 'ASSET'},
    {'code': '1120', 'name': 'Petty Cash Fund', 'type': 'ASSET'},
    {'code': '2100', 'name': 'Accounts Payable', 'type': 'LIABILITY'},
    {'code': '3100', 'name': 'Retained Earnings', 'type': 'EQUITY'},
    {'code': '4100', 'name': 'General Tithes & Offerings', 'type': 'REVENUE'},
    {'code': '4200', 'name': 'Campaign Donations', 'type': 'REVENUE'},
    {'code': '5100', 'name': 'Operational & Admin Expenses', 'type': 'EXPENSE'},
    {'code': '5300', 'name': 'Benevolence & Outreach', 'type': 'EXPENSE'},
]

def seed_existing_branches_chart_of_accounts(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    Account = apps.get_model('finance', 'Account')
    for branch in Branch.objects.all():
        for acc_data in DEFAULT_ACCOUNTS:
            Account.objects.get_or_create(
                branch=branch,
                code=acc_data['code'],
                defaults={
                    'name': acc_data['name'],
                    'type': acc_data['type'],
                    'cached_balance': 0.00
                }
            )

def rollback_seeded_chart_of_accounts(apps, schema_editor):
    Account = apps.get_model('finance', 'Account')
    Account.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_existing_branches_chart_of_accounts, rollback_seeded_chart_of_accounts),
    ]
