# Generated by Django 5.0.14 on 2026-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('satellite', 'Satellite')], default='satellite', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
