# Generated by Django 5.0.14 on 2026-06-16 18:54

import django.db.models.deletion
import django.utils.timezone
import members.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marriage_anniversary_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], default='Single', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id_passport', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Visitor', 'Visitor'), ('New Convert', 'New Convert'), ('Member', 'Member'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Transferred', 'Transferred'), ('Deceased', 'Deceased')], default='Visitor', max_length=20)),
                ('member_type', models.CharField(choices=[('Regular', 'Regular'), ('Leader', 'Leader'), ('Clergy', 'Clergy')], default='Regular', max_length=20)),
                ('baptism_status', models.CharField(choices=[('Not Baptized', 'Not Baptized'), ('Water Baptized', 'Water Baptized'), ('Holy Spirit Baptized', 'Holy Spirit Baptized')], default='Not Baptized', max_length=30)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('baptism_place', models.CharField(blank=True, max_length=255, null=True)),
                ('baptism_officiant', models.CharField(blank=True, max_length=255, null=True)),
                ('salvation_status', models.CharField(choices=[('Born Again', 'Born Again'), ('Seeking', 'Seeking')], default='Seeking', max_length=20)),
                ('salvation_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('emergency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pastoral_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('ministries', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('communication_preferences', models.JSONField(blank=True, default=members.models.default_communication_preferences)),
                ('donor_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Guest', 'Guest'), ('Non-Donor', 'Non-Donor')], default='Non-Donor', max_length=20)),
                ('recurring_giving_opt_in', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_members', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Guardian', 'Guardian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='members.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='members.member'),
        ),
        migrations.CreateModel(
            name='MemberLifecycleTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_changes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_timeline', to='members.member')),
            ],
        ),
    ]
