# Generated by Django 5.0.14 on 2026-06-23 11:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scripture_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sermon_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=15)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('speaker', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('Faith', 'Faith & Belief'), ('Grace', 'Grace & Mercy'), ('Hope', 'Hope & Future'), ('Salvation', 'Salvation & Redemption'), ('Family', 'Family & Relationships'), ('Love', 'Love & Fellowship'), ('Prayer', 'Prayer & Intercession'), ('Worship', 'Worship & Praise'), ('Leadership', 'Leadership & Service')], db_index=True, max_length=50)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sermons', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sermons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
