# Generated by Antigravity on 2026-06-23
from django.db import migrations
from django.utils import timezone
import datetime

def seed_sermons(apps, schema_editor):
    Sermon = apps.get_model('sermons', 'Sermon')
    Branch = apps.get_model('branches', 'Branch')
    User = apps.get_model('authentication', 'User')

    # Get branch-001
    try:
        branch = Branch.objects.get(id='branch-001')
    except Branch.DoesNotExist:
        # Fallback to HQ
        try:
            branch = Branch.objects.get(id='hq-branch')
        except Branch.DoesNotExist:
            return

    # Get a default pastor or superadmin as creator
    creator = User.objects.filter(role='super_admin').first()

    # Sermon 1: Walking in Grace (Featured)
    Sermon.objects.create(
        branch=branch,
        title="Walking in Grace",
        description="An deep exposition of Romans 5, exploring how God's unmerited favor redeems our failures and empowers our daily walk with Him.",
        scripture_reference="Romans 5:1-11",
        sermon_date=datetime.date.today() - datetime.timedelta(days=3),
        status="Published",
        video_url="https://www.w3schools.com/html/mov_bbb.mp4",
        audio_url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        speaker="Rev. David Kamau",
        category="Grace",
        featured=True,
        notes="## Sermon Outline\n1. **The Foundation of Peace (v. 1-2)**\n   - Justified by faith, we have peace with God through Jesus.\n   - We stand in grace and rejoice in the hope of God's glory.\n\n2. **The Purpose of Trials (v. 3-5)**\n   - Sufferings produce perseverance, character, and hope.\n   - God's love is poured into our hearts by the Holy Spirit.\n\n3. **The Demonstration of Love (v. 6-8)**\n   - Christ died for us while we were still sinners.\n\n### Reflection Questions\n1. How does knowing you are justified by faith change your daily relationship with God?\n2. In what areas of your life do you need to rely more on His grace rather than your own strength?",
        tags=["Grace", "Faith", "Salvation"],
        created_by=creator
    )

    # Sermon 2: The Power of Persistent Prayer
    Sermon.objects.create(
        branch=branch,
        title="The Power of Persistent Prayer",
        description="Discover how persistent, heartfelt prayer changes hearts, align us with God's will, and unleashes spiritual breakthroughs.",
        scripture_reference="Luke 18:1-8",
        sermon_date=datetime.date.today() - datetime.timedelta(days=10),
        status="Published",
        video_url="https://www.w3schools.com/html/mov_bbb.mp4",
        audio_url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        speaker="Rev. Grace Wanjiku",
        category="Prayer",
        featured=False,
        notes="## Outline\n1. **The Parable of the Persistent Widow**\n   - Cry out to Him night and day.\n   - God is quick to bring justice to His chosen ones.\n\n2. **Aligning with His Will**\n   - Prayer is not about bending God to our will, but bending our will to His.",
        tags=["Prayer", "Hope", "Breakthrough"],
        created_by=creator
    )

    # Sermon 3: Building a Solid Family Foundation
    Sermon.objects.create(
        branch=branch,
        title="Building a Solid Family Foundation",
        description="Practical and biblical principles for strengthening marriages and raising children in an atmosphere of love, respect, and faith.",
        scripture_reference="Joshua 24:14-18",
        sermon_date=datetime.date.today() - datetime.timedelta(days=17),
        status="Published",
        video_url="https://www.w3schools.com/html/mov_bbb.mp4",
        audio_url="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        speaker="Pastor Samuel Ochieng",
        category="Family",
        featured=False,
        notes="## Outline\n1. **Joshua's Declaration**\n   - Choose this day whom you will serve.\n   - As for me and my household, we will serve the Lord.\n\n2. **Mutual Respect & Love**\n   - Spouses and children walking in fellowship.",
        tags=["Family", "Love", "Fellowship"],
        created_by=creator
    )

def remove_sermons(apps, schema_editor):
    Sermon = apps.get_model('sermons', 'Sermon')
    Sermon.objects.filter(title__in=[
        "Walking in Grace",
        "The Power of Persistent Prayer",
        "Building a Solid Family Foundation"
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('sermons', '0001_initial'),
        ('authentication', '0002_seed_initial_data'),
    ]
    operations = [
        migrations.RunPython(seed_sermons, reverse_code=remove_sermons),
    ]
