# Generated by Django 5.0.14 on 2026-06-27 15:10

import django.db.models.deletion
import sermons.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_inquiry'),
        ('sermons', '0002_seed_sermons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='part_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/audio/', validators=[sermons.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/', validators=[sermons.validators.validate_thumbnail]),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='sermons/videos/', validators=[sermons.validators.validate_video]),
        ),
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sermons/series_covers/', validators=[sermons.validators.validate_thumbnail])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_series', to='branches.branch')),
            ],
            options={
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date', '-created_at'],
                'unique_together': {('branch', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.sermonseries'),
        ),
    ]
