# Generated by Django 5.0.14 on 2026-06-23 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_inquiry'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_time_visitor', models.BooleanField(default=True)),
                ('invited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_reason', models.TextField(blank=True, null=True)),
                ('spiritual_background', models.CharField(blank=True, max_length=100, null=True)),
                ('prayer_request', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_visitors', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_profile', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Following Up', 'Following Up'), ('Integrated', 'Integrated'), ('Inactive', 'Inactive')], db_index=True, default='New', max_length=20)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('Attendance Absentee', 'Attendance Absentee'), ('Attendance Visitor Scan', 'Attendance Visitor Scan'), ('Prayer Crisis', 'Prayer Crisis'), ('Event RSVP', 'Event RSVP')], db_index=True, default='Manual', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('integrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_pastor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_up_tickets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tickets', to='branches.branch')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='follow_up.visitorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactHistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('Meeting', 'Meeting'), ('Visit', 'Visit')], max_length=20)),
                ('notes', models.TextField()),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_follow_up_interactions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='follow_up.followupticket')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='follow_up.visitorprofile')),
            ],
        ),
    ]
