import { DASHBOARD_ROUTES } from "@/constants/routes";
import { ROLES, type Role } from "@/types/roles";

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",
  MEMBERS_VIEW: "members:view",
  MEMBERS_MANAGE: "members:manage",
  VISITORS_VIEW: "visitors:view",
  FOLLOW_UP_MANAGE: "follow_up:manage",
  SERMONS_VIEW: "sermons:view",
  SERMONS_MANAGE: "sermons:manage",
  EVENTS_VIEW: "events:view",
  EVENTS_MANAGE: "events:manage",
  LIVESTREAM_VIEW: "livestream:view",
  LIVESTREAM_MANAGE: "livestream:manage",
  PRAYER_VIEW: "prayer:view",
  PRAYER_MANAGE: "prayer:manage",
  DONATIONS_VIEW: "donations:view",
  DONATIONS_MANAGE: "donations:manage",
  DONATIONS_REPORT: "donations:report",
  TESTIMONIES_VIEW: "testimonies:view",
  TESTIMONIES_MANAGE: "testimonies:manage",
  MEDIA_VIEW: "media:view",
  MEDIA_MANAGE: "media:manage",
  SCRIPTURE_VIEW: "scripture:view",
  SCRIPTURE_MANAGE: "scripture:manage",
  CELEBRATIONS_VIEW: "celebrations:view",
  NOTIFICATIONS_VIEW: "notifications:view",
  ANALYTICS_VIEW: "analytics:view",
  ANALYTICS_FINANCIAL: "analytics:financial",
  SETTINGS_MANAGE: "settings:manage",
  USERS_MANAGE: "users:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PASTOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VISITORS_VIEW,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.SERMONS_VIEW,
    PERMISSIONS.SERMONS_MANAGE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.LIVESTREAM_VIEW,
    PERMISSIONS.LIVESTREAM_MANAGE,
    PERMISSIONS.PRAYER_VIEW,
    PERMISSIONS.PRAYER_MANAGE,
    PERMISSIONS.TESTIMONIES_VIEW,
    PERMISSIONS.TESTIMONIES_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.SCRIPTURE_VIEW,
    PERMISSIONS.SCRIPTURE_MANAGE,
    PERMISSIONS.CELEBRATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.CHURCH_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.VISITORS_VIEW,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_MANAGE,
    PERMISSIONS.SERMONS_VIEW,
    PERMISSIONS.SERMONS_MANAGE,
    PERMISSIONS.PRAYER_VIEW,
    PERMISSIONS.TESTIMONIES_VIEW,
    PERMISSIONS.TESTIMONIES_MANAGE,
    PERMISSIONS.SCRIPTURE_VIEW,
    PERMISSIONS.CELEBRATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.TREASURER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.DONATIONS_MANAGE,
    PERMISSIONS.DONATIONS_REPORT,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_FINANCIAL,
  ],
  [ROLES.MEDIA_TEAM]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.SERMONS_VIEW,
    PERMISSIONS.LIVESTREAM_VIEW,
    PERMISSIONS.LIVESTREAM_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SERMONS_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.LIVESTREAM_VIEW,
    PERMISSIONS.PRAYER_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
    PERMISSIONS.TESTIMONIES_VIEW,
    PERMISSIONS.SCRIPTURE_VIEW,
    PERMISSIONS.CELEBRATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [ROLES.VISITOR]: [
    PERMISSIONS.SERMONS_VIEW,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.LIVESTREAM_VIEW,
    PERMISSIONS.PRAYER_VIEW,
    PERMISSIONS.DONATIONS_VIEW,
  ],
};

const ROUTE_PERMISSIONS: Record<string, Permission> = {
  [DASHBOARD_ROUTES.ROOT]: PERMISSIONS.DASHBOARD_VIEW,
  [DASHBOARD_ROUTES.MEMBERS]: PERMISSIONS.MEMBERS_VIEW,
  [DASHBOARD_ROUTES.VISITORS]: PERMISSIONS.VISITORS_VIEW,
  [DASHBOARD_ROUTES.FOLLOW_UP]: PERMISSIONS.FOLLOW_UP_MANAGE,
  [DASHBOARD_ROUTES.SERMONS]: PERMISSIONS.SERMONS_VIEW,
  [DASHBOARD_ROUTES.EVENTS]: PERMISSIONS.EVENTS_VIEW,
  [DASHBOARD_ROUTES.LIVESTREAM]: PERMISSIONS.LIVESTREAM_VIEW,
  [DASHBOARD_ROUTES.PRAYER]: PERMISSIONS.PRAYER_VIEW,
  [DASHBOARD_ROUTES.DONATIONS]: PERMISSIONS.DONATIONS_VIEW,
  [DASHBOARD_ROUTES.TESTIMONIES]: PERMISSIONS.TESTIMONIES_VIEW,
  [DASHBOARD_ROUTES.MEDIA]: PERMISSIONS.MEDIA_VIEW,
  [DASHBOARD_ROUTES.SCRIPTURE]: PERMISSIONS.SCRIPTURE_VIEW,
  [DASHBOARD_ROUTES.CELEBRATIONS]: PERMISSIONS.CELEBRATIONS_VIEW,
  [DASHBOARD_ROUTES.NOTIFICATIONS]: PERMISSIONS.NOTIFICATIONS_VIEW,
  [DASHBOARD_ROUTES.ANALYTICS]: PERMISSIONS.ANALYTICS_VIEW,
  [DASHBOARD_ROUTES.SETTINGS]: PERMISSIONS.SETTINGS_MANAGE,
  [DASHBOARD_ROUTES.USERS]: PERMISSIONS.USERS_MANAGE,
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function hasAnyPermission(
  role: Role,
  permissions: Permission[],
): boolean {
  return permissions.some((permission) => hasPermission(role, permission));
}

export function canAccessRoute(role: Role, pathname: string): boolean {
  const normalizedPath = pathname.replace(/\/$/, "") || "/dashboard";

  const matchedRoute = Object.keys(ROUTE_PERMISSIONS)
    .sort((a, b) => b.length - a.length)
    .find((route) => normalizedPath.startsWith(route));

  if (!matchedRoute) {
    return hasPermission(role, PERMISSIONS.DASHBOARD_VIEW);
  }

  return hasPermission(role, ROUTE_PERMISSIONS[matchedRoute]);
}

export function getRolePermissions(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}
